language: node_js
node_js: 10

cache: yarn

install:
  - yarn

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: snyk
      script: yarn snyk test
    - stage: test
      script: yarn test
